# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Scripts that are called at very beginning, before repo cloning
init:
  # Fix line endings on Windows
  - git config --global core.autocrlf true

# Test against the LTS version of Node.js
environment:
  nodejs_version: "10"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry npm i

test_script:
  - npm run build
  - npm run check:qunit

after_test:
  # run audit to prevent adding vulnerable dependencies
  - ps: |
      if ($env:APPVEYOR_SCHEDULED_BUILD -eq 'True') {
        npm audit
      }

notifications:
  - provider: Email
    to:
      - limon.monte@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
