language: node_js
dist: xenial
node_js: lts/*
sudo: true

addons:
  firefox: latest
  chrome: stable

# limit the Travis 'build on push' feature to master and dist branches only
branches:
  only:
   - master
   - dist

install:
  - yarn install
  - yarn build

  # bundlesize
  - yarn global add bundlesize@^0.17.0
  - bundlesize -f dist/sweetalert2.all.min.js -s 15kB

  # prevent adding devDependencies with a shitload of subdependencies
  - if [ `yarn list | wc -l` -gt 4000 ]; then
      exit 1;
    fi

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      yarn run check;
    fi;

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      travis_retry yarn check:sauce &&
      yarn check:third-party;
    fi;

notifications:
  email:
    on_success: never

after_success:
  # update the dist branch to trigger the "release" task
  #- if [[ "$TRAVIS_BRANCH" = "master" ]]; then
  #    node tools/merge-master-into-dist;
  #  fi;

  # run automated release process with semantic-release
  #- if [[ "$TRAVIS_BRANCH" = "dist" ]]; then
  #    yarn global add semantic-release@16.0.0-beta.16 @semantic-release/changelog@3 @semantic-release/exec@3 @semantic-release/git@7;
  #    semantic-release;
  #  fi;

  # report coverage to coveralls.io and upload to transfer.sh
  - if [[ "$TRAVIS_BRANCH" != "dist" && "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      yarn global add coveralls@3;
      cat ./coverage/lcov.info | coveralls;
      zip -r coverage.zip coverage;
      curl --upload-file ./coverage.zip https://transfer.sh/coverage.zip;
    fi;
