language: node_js
dist: trusty
node_js: 8.9
sudo: true

addons:
  firefox: latest
  google-chrome: latest

before_script:
  - npm run build-dist
  - npm run check-bundlesize
  - npm run check-lint
  - npm run check-test
  - npm run check-dts

script:

deploy:
  api_key:
    secure: TaF0rF0+n/t3jchds6RSahdIwV+VozFEzGXdnwKzX8TnW2afGU7hh50BJHdQA6/mm0VbgxwAfIDMYU2luLwQn8CJCcJYp7g3+g8xsH15q8ny2AUmIkQQ2sWY43Vk1yMHIwzuAlHy5Pv5qKk8cYRVY5fwaCl/4KfvpIn4F2/DjwU=
  email: limon.monte@gmail.com
  provider: npm

notifications:
  email:
    on_success: never
