language: node_js
dist: trusty
node_js: 8.9
sudo: true

addons:
  firefox: latest
  google-chrome: latest

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

script:
  # xvfb-run is needed for headless testing with real browsers
  - xvfb-run yarn test

after_script:
  - greenkeeper-lockfile-upload

notifications:
  email:
    on_success: never
