name: Test Chrome

on:
  push:

jobs:
  Chrome:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run build

      - run: bun lint

      - run: bun check-types

      # - name: Run tests in Chrome
      #   run: bun run test --browser chrome

      # - name: Test in CommonJS
      #   if: github.ref_name == 'main'
      #   run: node test/require-in-commonjs.cjs

      - name: Test with Webpack
        if: github.ref_name == 'main'
        run: |
          bun add --dev webpack@^5.0.0 webpack-cli@^5.0.0
          bun webpack-build
          bun add --dev webpack@^4.0.0 webpack-cli@^4.0.0
          export NODE_OPTIONS=--openssl-legacy-provider
          bun webpack-build

      - name: Check TypeScript
        if: github.ref_name == 'main'
        run: |
          ln -s ../../ test/ts/node_modules
          tsc --lib dom,es6 --skipLibCheck --noEmit --strict test/ts/simple-usage.ts
          tsc --lib dom,es6 --skipLibCheck --noEmit --strict test/ts/inputValidator.ts
          tsc --lib dom,es6 --skipLibCheck --noEmit --strict test/ts/dist-sweetalert2.ts sweetalert2.d.ts
          tsc --lib dom,es6 --skipLibCheck --noEmit --strict test/ts/src-sweetalert2.ts sweetalert2.d.ts

      - name: Run automated release process with semantic-release
        if: github.ref_name == 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
